using System.Diagnostics.CodeAnalysis;

namespace Typst.Net.Core;

/// <summary>
/// Represents the result of a Typst operation, containing the output data and any standard error messages.
/// </summary>
/// <param name="OutputData">
/// A <see cref="MemoryStream"/> containing the output data generated by the Typst operation.
/// </param>
/// <param name="StandardError">
/// A <see cref="string"/> containing any error messages or diagnostic information produced during the Typst operation.
/// </param>
[ExcludeFromCodeCoverage]
public sealed record TypstResult(MemoryStream OutputData, string StandardError);
